import { Link, useParams } from 'react-router-dom'
import { api } from '../lib/api'
import { useAsync } from '../lib/useAsync'
import {
  CiteBlock, CopyField, ErrorState, FairDownloads, ForeignNotice, Skeleton, Tombstone, formatBytes,
} from '../components/common'
import { ArtifactTypeChip, AvailabilityBadge, LicenseChip, OriginChip, RelativeTime } from '../components/chips'
import type { Distribution } from '../lib/types'

export default function ArtifactDetail() {
  const { id = '' } = useParams()
  const art = useAsync(() => api.getArtifact(id), [id])
  const lin = useAsync(() => api.lineage(id, 1), [id])

  if (art.loading) return <Skeleton rows={8} />
  if (art.error) return <ErrorState error={art.error} onRetry={art.reload} />
  if (!art.data) return null
  const a = art.data
  const foreign = a.origin.kind === 'peer'
  const downstream = (lin.data?.edges ?? []).filter((e) => e.to === a.iri && e.predicate !== 'generated')

  return (
    <>
      {a.tombstoned && <Tombstone what="artifact record" />}
      {foreign && <ForeignNotice homeIri={a.iri} />}

      <div className="detail">
        <div>
          <div className="page-header">
            <div className="spread">
              <h1>{a.title ?? 'Untitled artifact'}</h1>
              <OriginChip origin={a.origin} />
            </div>
            <ul className="chips">
              {a.conforms_to && <li><ArtifactTypeChip type={a.conforms_to} /></li>}
              <li><AvailabilityBadge availability={a.availability} /></li>
              <li><LicenseChip license={a.license} /></li>
            </ul>
          </div>

          {a.description && <p>{a.description}</p>}

          <section className="card">
            <h2>Distributions</h2>
            {a.distributions.length === 0 ? (
              <p className="muted">
                No distribution is described. The artifact is recorded as existing, with its
                provenance, but there is no stated way to reach it.
              </p>
            ) : (
              <div className="stack">
                {a.distributions.map((d) => <DistributionCard key={d.iri} d={d} />)}
              </div>
            )}
          </section>

          <section className="card">
            <h2>Provenance</h2>
            {a.generated_by_run ? (
              <p style={{ marginTop: 0 }}>
                Generated by run{' '}
                <Link to={`/runs/${a.generated_by_run.id}`} className="mono">{a.generated_by_run.id.slice(0, 8)}</Link>
                {a.generated_by_run.instance && (
                  <> at <Link to={`/instances/${a.generated_by_run.instance.split('/').pop()}`}>
                    {a.generated_by_run.instance_label ?? 'a deployment'}
                  </Link></>
                )}
                {a.generated_by_run.software && a.generated_by_run.software_name && (
                  <> running <Link to={`/software/${a.generated_by_run.software.split('/').pop()}`}>
                    {a.generated_by_run.software_name}
                  </Link></>
                )}
                {a.generated_by_run.release_version && <> {a.generated_by_run.release_version}</>}
                {a.generated_by_run.ended_at && <> · <RelativeTime iso={a.generated_by_run.ended_at} /></>}
              </p>
            ) : (
              <p className="muted" style={{ marginTop: 0 }}>
                No run is recorded for this artifact — it was registered directly.
              </p>
            )}

            <div className="two-col" style={{ marginTop: 14 }}>
              <div>
                <h3 style={{ fontSize: 13, margin: '0 0 6px' }}>Derived from</h3>
                {a.was_derived_from.length ? (
                  <ul>
                    {a.was_derived_from.map((p) => <li key={p}><LineageLink iri={p} /></li>)}
                  </ul>
                ) : (
                  <p className="muted">Nothing recorded.</p>
                )}
              </div>
              <div>
                <h3 style={{ fontSize: 13, margin: '0 0 6px' }}>Used downstream by</h3>
                {downstream.length ? (
                  <ul>
                    {downstream.map((e) => <li key={e.from}><LineageLink iri={e.from} /></li>)}
                  </ul>
                ) : (
                  <p className="muted">Nothing recorded.</p>
                )}
              </div>
            </div>
            {lin.data?.truncated && (
              <p className="hint">Lineage continues beyond this depth.</p>
            )}
          </section>

          {(a.was_revision_of || a.is_version_of) && (
            <section className="card">
              <h2>Versions</h2>
              <p className="hint" style={{ marginTop: 0 }}>
                Artifacts are immutable once advertised. A correction mints a new IRI and links
                back, so an existing lineage edge never silently changes meaning.
              </p>
              <dl className="rail-section">
                {a.was_revision_of && (
                  <>
                    <dt>Revision of</dt>
                    <dd><LineageLink iri={a.was_revision_of} /></dd>
                  </>
                )}
                {a.is_version_of && (
                  <>
                    <dt>Version series</dt>
                    <dd className="mono" style={{ fontSize: 12 }}>{a.is_version_of}</dd>
                  </>
                )}
              </dl>
            </section>
          )}
        </div>

        <aside className="rail">
          <section className="card rail-section">
            <h2>Persistent IRI</h2>
            <CopyField value={a.iri} label="persistent IRI" />
            <dl>
              <dt>Issued</dt>
              <dd><RelativeTime iso={a.issued} /></dd>
              {a.publisher && (
                <>
                  <dt>Publisher</dt>
                  <dd>{a.publisher.name ?? a.publisher.iri}</dd>
                </>
              )}
              {a.external_key && (
                <>
                  <dt>External key</dt>
                  <dd className="mono" style={{ fontSize: 12 }}>{a.external_key}</dd>
                </>
              )}
              {a.keywords.length > 0 && (
                <>
                  <dt>Keywords</dt>
                  <dd><ul className="chips">{a.keywords.map((k) => <li key={k}><span className="chip plain">{k}</span></li>)}</ul></dd>
                </>
              )}
            </dl>
          </section>
          <CiteBlock iri={a.iri} title={a.title ?? a.id} />
          <FairDownloads iri={a.iri} />
        </aside>
      </div>
    </>
  )
}

function DistributionCard({ d }: { d: Distribution }) {
  const metadataOnly = d.availability === 'metadata-only'
  return (
    <div className="card" style={{ margin: 0, background: 'var(--surface-2)' }}>
      <div className="spread" style={{ marginBottom: 8 }}>
        <strong>{d.title ?? d.media_type ?? 'Distribution'}</strong>
        <AvailabilityBadge availability={d.availability} />
      </div>

      {/* A metadata-only distribution renders no download affordance at all — not a disabled
          one, which would miscommunicate (handoff §5.5). */}
      {metadataOnly ? (
        <div className="banner info" style={{ marginBottom: 8 }}>
          <p>
            The bytes are not published here. The record exists so the artifact is findable and
            its provenance is readable.
          </p>
        </div>
      ) : (
        <ul className="chips" style={{ marginBottom: 8 }}>
          {d.download_url && <li><a className="chip accent" href={d.download_url}>⬇ Download</a></li>}
          {d.access_url && <li><a className="chip" href={d.access_url} target="_blank" rel="noreferrer">Access page ↗</a></li>}
        </ul>
      )}

      {d.access_request_url && (
        <a className="chip accent" href={d.access_request_url} target="_blank" rel="noreferrer">Request access ↗</a>
      )}

      <dl className="rail-section">
        {d.media_type && (<><dt>Media type</dt><dd className="mono">{d.media_type}</dd></>)}
        {d.byte_size !== undefined && (<><dt>Size</dt><dd>{formatBytes(d.byte_size)}</dd></>)}
        {d.conforms_to && (<><dt>Conforms to</dt><dd><a href={d.conforms_to}>{d.conforms_to}</a></dd></>)}
        <dt>Access</dt>
        <dd>
          <ul className="chips">
            {d.access_protocol && <li><span className="chip">{d.access_protocol}</span></li>}
            {d.auth_method && <li><span className="chip">auth: {d.auth_method}</span></li>}
          </ul>
        </dd>
        {d.checksum && (
          <>
            <dt>Checksum ({d.checksum.algorithm})</dt>
            <dd><CopyField value={d.checksum.value} label="checksum" /></dd>
          </>
        )}
      </dl>
    </div>
  )
}

/** A lineage neighbour: local records link into the UI, foreign ones link to their home. */
function LineageLink({ iri }: { iri: string }) {
  const local = iri.startsWith(window.location.origin)
  if (local) {
    const path = iri.slice(window.location.origin.length).replace('/artifact/', '/artifacts/')
    return <Link to={path} className="mono" style={{ fontSize: 12.5 }}>{iri.split('/').pop()}</Link>
  }
  return (
    <span className="inline">
      <a href={iri} target="_blank" rel="noreferrer" className="mono" style={{ fontSize: 12.5 }}>{iri}</a>
      <span className="chip peer">peer</span>
    </span>
  )
}
